[package]
name = "lgtm-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "crates/app-server-client", "crates/output"]
resolver = "3"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
lgtm-app-server-client = { path = "crates/app-server-client" }
lgtm-output = { path = "crates/output" }
